"""NavDP GRPO fine-tuning default config (aligned with JdInternNav)."""

from autonomy_internnav.train.configs.eval import EvalCfg
from autonomy_internnav.train.configs.exp import ExpCfg
from autonomy_internnav.train.configs.grpo import GrpoCfg, RewardCfg
from autonomy_internnav.train.configs.il import FilterFailure, IlCfg, Loss
from autonomy_internnav.train.configs.model import ModelCfg

navdp_cfg = ModelCfg(policy_name='NavDPGRPO_Policy')

navdp_grpo_exp_cfg = ExpCfg(
    name='navdp_grpo_train',
    model_name='navdp_grpo',
    torch_gpu_id=0,
    torch_gpu_ids=[0],
    output_dir='checkpoints/%s/ckpts',
    tensorboard_dir='checkpoints/%s/tensorboard',
    checkpoint_folder='checkpoints/%s/ckpts',
    log_dir='checkpoints/%s/logs',
    local_rank=0,
    seed=0,
    eval=EvalCfg(
        use_ckpt_config=False,
        save_results=True,
        split=['val_seen'],
        ckpt_to_load='',
        max_steps=195,
        sample=False,
        success_distance=0.3,
        start_eval_epoch=-1,
        step_interval=50,
    ),
    il=IlCfg(
        epochs=1000,
        batch_size=32,
        lr=1e-4,
        num_workers=8,
        gradient_accumulation_steps=4,
        weight_decay=1e-4,
        warmup_ratio=0.05,
        use_iw=True,
        inflection_weight_coef=3.2,
        save_interval_epochs=5,
        save_total_limit=None,
        save_filter_frozen_weights=False,
        load_from_ckpt=False,
        ckpt_to_load='',
        lmdb_map_size=1e12,
        dataset_r2r_root_dir='data/vln_pe/raw_data/r2r',
        dataset_3dgs_root_dir='',
        dataset_grutopia10_root_dir='',
        lmdb_features_dir='r2r',
        lerobot_features_dir='data/vln_pe/traj_data/r2r',
        dataset_format='v2',
        camera_name='pano_camera_0',
        report_to='tensorboard',
        dataset_navdp='data/datasets/navdp_dataset_lerobot.json',
        root_dir='data/datasets/InternData-N1/vln_n1/traj_data',
        image_size=224,
        scene_scale=1.0,
        preload=False,
        random_digit=False,
        prior_sample=False,
        target_segment_weights=None,
        dataset_repeat=1,
        memory_size=8,
        predict_size=24,
        pixel_channel=4,
        temporal_depth=16,
        heads=8,
        token_dim=384,
        channels=3,
        dropout=0.1,
        scratch=False,
        finetune=False,
        ddp_find_unused_parameters=True,
        filter_failure=FilterFailure(use=True, min_rgb_nums=15),
        loss=Loss(alpha=0.0001, dist_scale=1),
    ),
    grpo=GrpoCfg(
        adv_type='grpo',
        loss_type='actor',
        group_size=8,
        normalize_advantages=True,
        clip_ratio_low=0.2,
        clip_ratio_high=0.28,
        kl_beta=0.0,
        entropy_bonus=0.0,
        use_ref_policy=True,
        filter_rewards=False,
        rewards_lower_bound=-1e9,
        rewards_upper_bound=1e9,
        num_inner_epochs=1,
        rollout_batch_size=4,
        num_rollout_iters=100,
        gradient_accumulation_steps=4,
        rollout_num_inference_steps=None,
        joint_logprob=False,
        sample_step_subset=None,
        lr=5e-5,
        weight_decay=0.0,
        max_grad_norm=1.0,
        goal_type='point',
        critic_weight=0.0,
        critic_use_augment=True,
        freeze_encoder=True,
        freeze_dit_layers=11,
        freeze_critic=True,
        reward=RewardCfg(
            type='composite',
            collision_weight=-5.0,
            occupancy_weight=-1.0,
            success_weight=10.0,
            progress_weight=3.0,
        ),
        log_every=1,
        save_every_iters=50,
        special_trajectory_index_path=None,
        uturn_mix_ratio=0.0,
        sharp_turn_mix_ratio=0.0,
        special_allow_cross_scene_fallback=True,
    ),
    model=navdp_cfg,
)
