uint16 UNKNOWN_CONTROLTYPE = 0
# 左右摇头
uint16 HEAD_SHAKE = 100
# 头回正
uint16 HEAD_CENTER = 101

# 上肢回正
uint16 UPPER_BODY_CENTER = 200
# 抬左手90° 上下律动+腰
uint16 BODY_RHYTHMIC_90_L = 201
# 抬右手90° 上下律动+腰
uint16 BODY_RHYTHMIC_90_R = 202
# 抬左手90° 上下律动
uint16 ARM_RHYTHMIC_90_L = 203
# 抬右手90° 上下律动
uint16 ARM_RHYTHMIC_90_R = 204
# 抬左手180° 上下律动
uint16 ARM_RHYTHMIC_180_L = 205
# 抬右手180° 上下律动
uint16 ARM_RHYTHMIC_180_R = 206
# 左手90°画圈
uint16 LEFT_ARM_CIRCLE_90 = 207
# 右手90°画圈
uint16 RIGHT_ARM_CIRCLE_90 = 208
# 左手160°画圈
uint16 LEFT_ARM_CIRCLE_160 = 209
# 右手160°画圈
uint16 RIGHT_ARM_CIRCLE_160 = 210
# 左右手错位律动
uint16 ALTERNATE_RHYTHMIC = 211
# 企鹅手
uint16 PENGUIN_ARM = 212
# 双臂打开
uint16 ARMS_OPEN = 213
# 交替挥臂
uint16 ALTERNATE_SWING = 214
# 双臂举手挥拳
uint16 ARMS_RAISE_PUNCH = 215
# 左右手同时90°画圈
uint16 ARMS_CIRCLE_90 = 216
# 左右手同时160°画圈
uint16 ARMS_CIRCLE_160 = 217

# 下肢回正
uint16 LOWER_BODY_CENTER = 300
# 原地转圈
uint16 SPIN_IN_PLACE = 301
# 律动抖腿
uint16 RHYTHMIC_LEG_SHAKE = 302
# 太空步
uint16 MOONWALK = 303
# roll摆
uint16 ROLL_SWING = 304
# 上身弯腰
uint16 BOW = 305

uint16 type