# Single-goal navigation (/autonomy/navigate_pose).

string task_id
geometry_msgs/PoseStamped goal
string behavior_tree
---
Error error
nav_msgs/Path path
builtin_interfaces/Duration navigation_time
---
geometry_msgs/PoseStamped current_pose
float32 distance_remaining
builtin_interfaces/Duration navigation_time
